[features]
seeds = false
skip-lint = false


[programs.localnet]
voltchain = "718k7JFp8Tf56eMTpTJMqmwNxME738nh48bXCiCm1BrR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"